# Generated by Django 6.0.5 on 2026-07-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistafter',
            name='sig_ce',
            field=models.TextField(blank=True, verbose_name='Podpis CE'),
        ),
        migrations.AddField(
            model_name='checklistafter',
            name='sig_pp',
            field=models.TextField(blank=True, verbose_name='Podpis PP'),
        ),
        migrations.AddField(
            model_name='checklistafter',
            name='sig_qa',
            field=models.TextField(blank=True, verbose_name='Podpis QA'),
        ),
        migrations.AddField(
            model_name='checklistafter',
            name='sig_ql',
            field=models.TextField(blank=True, verbose_name='Podpis QL'),
        ),
        migrations.AddField(
            model_name='checklistafter',
            name='sig_rd',
            field=models.TextField(blank=True, verbose_name='Podpis R&D'),
        ),
        migrations.AddField(
            model_name='checklistafter',
            name='sig_sc',
            field=models.TextField(blank=True, verbose_name='Podpis SC'),
        ),
        migrations.AddField(
            model_name='checklistafter',
            name='sig_sdp',
            field=models.TextField(blank=True, verbose_name='Podpis SDP'),
        ),
        migrations.AlterField(
            model_name='checklistafter',
            name='acceptance_signature',
            field=models.TextField(blank=True, verbose_name='Podpis SD'),
        ),
    ]
