# Generated by Django 6.0.5 on 2026-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_checklistafter_sig_ce_checklistafter_sig_pp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistafter',
            name='sig_sd',
            field=models.TextField(blank=True, verbose_name='Podpis SD'),
        ),
    ]
