# Generated by Django 6.0.7 on 2026-07-24 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0003_checklistafter_sig_sd"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Adres email"
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="Opis"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Aktywny")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Stały odbiorca (pierwsza produkcja)",
                "verbose_name_plural": "Stali odbiorcy (pierwsza produkcja)",
                "ordering": ["email"],
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="chip_number",
            field=models.CharField(
                blank=True,
                help_text="5-cyfrowy numer używany do logowania (zamiast hasła).",
                max_length=5,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{5}$", "Numer chip musi składać się z dokładnie 5 cyfr."
                    )
                ],
                verbose_name="Numer chip",
            ),
        ),
        migrations.AlterField(
            model_name="firstproduction",
            name="status",
            field=models.CharField(
                choices=[
                    ("nowa", "Nowa"),
                    ("etap1", "Etap I"),
                    ("etap2", "Etap II – Produkcja"),
                    ("etap3", "Etap III – Test pakowania"),
                    ("zwolniona", "Zwolniona do sprzedaży"),
                ],
                default="nowa",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
