# Generated by Django 6.0.7 on 2026-07-24 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0004_notificationrecipient_userprofile_chip_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="email_logs",
                to="productions.firstproduction",
            ),
        ),
    ]
