# Generated by Django 6.0.7 on 2026-07-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0005_alter_emaillog_production"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstproduction",
            name="reminder_sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data wysłania przypomnienia"
            ),
        ),
    ]
