# Generated by Django 5.2.17 on 2026-08-04 17:20 (hand-edited: SDP -> WPD kept
# as renames so existing data survives, instead of the autodetector's default
# remove+add; added a data migration for UserProfile.department values).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _sdp_department_to_wpd(apps, schema_editor):
    UserProfile = apps.get_model('productions', 'UserProfile')
    UserProfile.objects.filter(department='SDP').update(department='WPD')


def _wpd_department_to_sdp(apps, schema_editor):
    UserProfile = apps.get_model('productions', 'UserProfile')
    UserProfile.objects.filter(department='WPD').update(department='SDP')


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0006_firstproduction_reminder_sent_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ── SDP -> WPD: zmiana nazwy działu (dane zachowane) ──
        migrations.RenameField(
            model_name="checklistafter",
            old_name="person_sdp",
            new_name="person_wpd",
        ),
        migrations.AlterField(
            model_name="checklistafter",
            name="person_wpd",
            field=models.CharField(blank=True, max_length=100, verbose_name="WPD"),
        ),
        migrations.RenameField(
            model_name="checklistafter",
            old_name="sig_sdp",
            new_name="sig_wpd",
        ),
        migrations.AlterField(
            model_name="checklistafter",
            name="sig_wpd",
            field=models.TextField(blank=True, verbose_name="Podpis WPD"),
        ),
        migrations.RenameField(
            model_name="checklistbefore",
            old_name="confirm_sdp",
            new_name="confirm_wpd",
        ),
        migrations.AlterField(
            model_name="checklistbefore",
            name="confirm_wpd",
            field=models.CharField(blank=True, max_length=100, verbose_name="Podpis WPD"),
        ),
        migrations.RenameField(
            model_name="firstproduction",
            old_name="person_sdp",
            new_name="person_wpd",
        ),
        migrations.AlterField(
            model_name="firstproduction",
            name="person_wpd",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_wpd",
                to=settings.AUTH_USER_MODEL,
                verbose_name="WPD",
            ),
        ),
        migrations.RunPython(_sdp_department_to_wpd, _wpd_department_to_sdp),

        # ── Nowy dział Technologia (TE) ──
        migrations.AddField(
            model_name="checklistafter",
            name="person_te",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Technologia"
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_te",
            field=models.TextField(blank=True, verbose_name="Podpis Technologia"),
        ),
        migrations.AddField(
            model_name="firstproduction",
            name="person_te",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_te",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Technologia",
            ),
        ),

        # ── Decyzja SD (Akceptacja / Akceptacja warunkowa / Do korekty) ──
        migrations.AddField(
            model_name="checklistafter",
            name="conditional_comment",
            field=models.TextField(
                blank=True, verbose_name="Komentarz (akceptacja warunkowa)"
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="correction_comment",
            field=models.TextField(blank=True, verbose_name="Komentarz (do korekty)"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="correction_return_stage",
            field=models.CharField(
                blank=True,
                choices=[("sensory", "Sensoryka"), ("packaging", "Pakownia")],
                max_length=10,
                verbose_name="Powrót do etapu",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="decision",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accept", "Akceptacja"),
                    ("conditional", "Akceptacja warunkowa"),
                    ("correction", "Do korekty"),
                ],
                max_length=15,
                verbose_name="Decyzja",
            ),
        ),

        # ── Zakres produkcji (sensoryka / pakowanie / oba) + powiązanie ──
        migrations.AddField(
            model_name="firstproduction",
            name="fert_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Numer FERT"
            ),
        ),
        migrations.AddField(
            model_name="firstproduction",
            name="linked_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Data powiązania"
            ),
        ),
        migrations.AddField(
            model_name="firstproduction",
            name="linked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Powiązano przez",
            ),
        ),
        migrations.AddField(
            model_name="firstproduction",
            name="linked_production",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="productions.firstproduction",
                verbose_name="Powiązana produkcja",
            ),
        ),
        migrations.AddField(
            model_name="firstproduction",
            name="scope",
            field=models.CharField(
                choices=[
                    ("full", "Produkcja z sensoryką i pakowaniem"),
                    ("sensory", "Tylko produkcja (sensoryka)"),
                    ("packaging", "Tylko pakowanie"),
                ],
                default="full",
                max_length=10,
                verbose_name="Zakres produkcji",
            ),
        ),

        # ── Zmiana etykiety pola ──
        migrations.AlterField(
            model_name="firstproduction",
            name="rd_number",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nr receptury R&D"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "R&D"),
                    ("SC", "SC"),
                    ("QL", "QL"),
                    ("QA", "QA"),
                    ("SD", "SD"),
                    ("WPD", "WPD"),
                    ("PP", "PP"),
                    ("CE", "CE"),
                    ("TE", "Technologia"),
                ],
                max_length=10,
                verbose_name="Dział",
            ),
        ),
    ]
