# Generated by Django 6.0.8 on 2026-08-05 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0007_remove_checklistafter_person_sdp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="phone",
        ),
    ]
