# Generated by Django 6.0.8 on 2026-08-05 18:14 (hand-edited: clear
# UserProfile.department for any existing WPD users before the choice
# disappears, so they don't end up with an orphaned/invalid department code).

from django.db import migrations, models


def _clear_wpd_department(apps, schema_editor):
    UserProfile = apps.get_model('productions', 'UserProfile')
    UserProfile.objects.filter(department='WPD').update(department='')


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0008_remove_userprofile_phone"),
    ]

    operations = [
        migrations.RunPython(_clear_wpd_department, _noop_reverse),
        migrations.RemoveField(
            model_name="checklistafter",
            name="person_wpd",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_wpd",
        ),
        migrations.RemoveField(
            model_name="checklistbefore",
            name="confirm_wpd",
        ),
        migrations.RemoveField(
            model_name="firstproduction",
            name="person_wpd",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "R&D"),
                    ("SC", "SC"),
                    ("QL", "QL"),
                    ("QA", "QA"),
                    ("SD", "SD"),
                    ("PP", "PP"),
                    ("CE", "CE"),
                    ("TE", "Technologia"),
                ],
                max_length=10,
                verbose_name="Dział",
            ),
        ),
    ]
