# Generated by Django 5.2.7 on 2026-08-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0009_remove_checklistafter_person_wpd_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auth_code_hash",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Hash kodu autoryzującego"
            ),
        ),
    ]
