# Generated by Django 5.2.7 on 2026-08-11 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0010_userprofile_auth_code_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistafter",
            name="person_te",
            field=models.CharField(blank=True, max_length=100, verbose_name="PT"),
        ),
        migrations.AlterField(
            model_name="checklistafter",
            name="sig_te",
            field=models.TextField(blank=True, verbose_name="Podpis PT"),
        ),
        migrations.AlterField(
            model_name="firstproduction",
            name="person_te",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_te",
                to=settings.AUTH_USER_MODEL,
                verbose_name="PT",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "R&D"),
                    ("SC", "SC"),
                    ("QL", "QL"),
                    ("QA", "QA"),
                    ("SD", "SD"),
                    ("PP", "PP"),
                    ("CE", "CE"),
                    ("TE", "PT"),
                ],
                max_length=10,
                verbose_name="Dział",
            ),
        ),
    ]
