# Generated by Django 5.2.7 on 2026-08-11 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0011_alter_checklistafter_person_te_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_ce",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_pp",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_qa",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_ql",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_rd",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_sc",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_sd",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="sig_te",
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="person_sl",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Sprzedaż Lubeck"
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_ce",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie CE",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_pp",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie PP",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_qa",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie QA",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_ql",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie QL",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_rd",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie R&D",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_sc",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie SC",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_sd",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie SD",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_sl",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie Sprzedaż Lubeck",
            ),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="photo_te",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="team_photos/",
                verbose_name="Zdjęcie PT",
            ),
        ),
        migrations.AddField(
            model_name="firstproduction",
            name="person_sl",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prod_sl",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Sprzedaż Lubeck",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "R&D"),
                    ("SC", "SC"),
                    ("QL", "QL"),
                    ("QA", "QA"),
                    ("SD", "SD"),
                    ("PP", "PP"),
                    ("CE", "CE"),
                    ("TE", "PT"),
                    ("SL", "Sprzedaż Lubeck"),
                ],
                max_length=10,
                verbose_name="Dział",
            ),
        ),
    ]
