# Generated by Django 5.2.7 on 2026-08-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0012_remove_checklistafter_sig_ce_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RD", "R&D"),
                    ("SC", "SC"),
                    ("QL", "QL"),
                    ("QA", "QA"),
                    ("SD", "SD"),
                    ("PP", "PP"),
                    ("CE", "CE"),
                    ("TE", "PT"),
                    ("SL", "Sprzedaż Lubeck"),
                    ("IT", "IT"),
                ],
                max_length=10,
                verbose_name="Dział",
            ),
        ),
    ]
