# Generated by Django 5.2.7 on 2026-08-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0013_alter_userprofile_department"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_ce",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_pp",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_qa",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_ql",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_rd",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_sc",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_sd",
        ),
        migrations.RemoveField(
            model_name="checklistafter",
            name="photo_te",
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_ce",
            field=models.TextField(blank=True, verbose_name="Podpis CE"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_pp",
            field=models.TextField(blank=True, verbose_name="Podpis PP"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_qa",
            field=models.TextField(blank=True, verbose_name="Podpis QA"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_ql",
            field=models.TextField(blank=True, verbose_name="Podpis QL"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_rd",
            field=models.TextField(blank=True, verbose_name="Podpis R&D"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_sc",
            field=models.TextField(blank=True, verbose_name="Podpis SC"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_sd",
            field=models.TextField(blank=True, verbose_name="Podpis SD"),
        ),
        migrations.AddField(
            model_name="checklistafter",
            name="sig_te",
            field=models.TextField(blank=True, verbose_name="Podpis PT"),
        ),
    ]
