# Generated by Django 5.2.7 on 2026-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0014_remove_checklistafter_photo_ce_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="recipient",
            field=models.TextField(),
        ),
    ]
