# Generated by Django 5.2.17 on 2026-09-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0015_alter_emaillog_recipient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensoryparam",
            name="param",
            field=models.CharField(
                choices=[
                    ("smak", "Smak"),
                    ("zapach", "Zapach"),
                    ("wyglad", "Wygląd"),
                    ("kolor", "Kolor"),
                    ("tekstura", "Tekstura"),
                    ("gestosc", "Gęstość usypowa"),
                    ("wilgotnosc", "Wilgotność"),
                ],
                max_length=20,
            ),
        ),
    ]
