# Generated by Django 5.2.17 on 2026-09-10 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0017_backfill_wilgotnosc_sensory_param"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistafter",
            name="lab_samples_delivered",
            field=models.CharField(
                blank=True,
                choices=[("tak", "Tak"), ("nie", "Nie")],
                max_length=3,
                verbose_name="Czy dostarczono próbki do laboratorium?",
            ),
        ),
    ]
