# Generated by Django 5.2.17 on 2026-09-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0018_checklistafter_lab_samples_delivered"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistafter",
            name="umk_uwagi",
            field=models.TextField(blank=True, verbose_name="Uwagi (UMK)"),
        ),
        migrations.AddField(
            model_name="checklistbefore",
            name="additional_samples_uwagi",
            field=models.TextField(
                blank=True, verbose_name="Uwagi (dodatkowe próbki/UMK)"
            ),
        ),
    ]
