# Generated by Django 5.2.17 on 2026-09-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0019_checklistafter_umk_uwagi_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="firstproduction",
            name="reminder_24h_sent_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Data wysłania przypomnienia 24h przed",
            ),
        ),
    ]
