# Generated by Django 5.2.17 on 2026-09-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0020_firstproduction_reminder_24h_sent_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklistbefore",
            name="confirm_ce",
        ),
        migrations.AddField(
            model_name="checklistbefore",
            name="confirm_ql",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził QL"
            ),
        ),
        migrations.AddField(
            model_name="checklistbefore",
            name="confirm_sc",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził SC"
            ),
        ),
        migrations.AddField(
            model_name="checklistbefore",
            name="confirm_te",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził PT"
            ),
        ),
        migrations.AlterField(
            model_name="checklistbefore",
            name="confirm_pp",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził PP"
            ),
        ),
        migrations.AlterField(
            model_name="checklistbefore",
            name="confirm_qa",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził QA"
            ),
        ),
        migrations.AlterField(
            model_name="checklistbefore",
            name="confirm_rd",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził R&D"
            ),
        ),
        migrations.AlterField(
            model_name="checklistbefore",
            name="confirm_sd",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził SD"
            ),
        ),
    ]
