# Generated by Django 5.2.17 on 2026-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0021_remove_checklistbefore_confirm_ce_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistafter",
            name="sensory_completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
