# Generated by Django 5.2.17 on 2026-09-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0022_checklistafter_sensory_completed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bulk_emails_enabled",
                    models.BooleanField(
                        default=True,
                        verbose_name="Wysyłka maili do grupy mailowej włączona",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ustawienia email",
                "verbose_name_plural": "Ustawienia email",
            },
        ),
        migrations.AddField(
            model_name="emaillog",
            name="skipped",
            field=models.BooleanField(
                default=False, verbose_name="Pominięty (tryb testowy)"
            ),
        ),
    ]
