# Generated by Django 5.2.17 on 2026-09-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0023_emailsettings_emaillog_skipped"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklistafter",
            name="lab_samples_delivered",
            field=models.CharField(
                blank=True,
                choices=[("tak", "Tak"), ("nie", "Nie")],
                default="nie",
                max_length=3,
                verbose_name="Czy dostarczono próbki do laboratorium?",
            ),
        ),
    ]
