# Generated by Django 5.2.17 on 2026-09-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("productions", "0025_backfill_lab_samples_delivered_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="checklistbefore",
            name="confirm_ce",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Potwierdził CE"
            ),
        ),
    ]
